spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/MessageQueue
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: TRACE
            StatementCreatorUtils: TRACE

    